### PR TITLE
WIP: Auto black

### PR DESCRIPTION
**Pull request by marianheil**

### CODE REVIEW

**Comment by scarlehoff** [comment]
Personally I'd say we want people to run black on their own computers.
If someone wants, for some reason (clarity or whatever), to have a line with 101 characters I think they should be able to have it.

**Comment by marianheil** [comment]
`black` gives the option to turn the parsing off with `# fmt: off`. This MR just simplifies committing by taking the formatting part away, in particular since with #69 we enforces pep8. However I don't think this is a must have. Whatever you prefer :wink:

**Comment by scarlehoff** [comment]
Well, you guys write to this repo way more than me these days, so if it makes your life easier...

The only permission the token needs is workflow, right? How do you plan too trigger the flake8 workflow?

Alternatively, wouldn't it make sense to run the workflow such that you do
- flake8 but only stop in actual python errors
- black (don't push)
- flake8 but now you are stopping also in not-pep8 mistakes
- then you push

Otherwise you will be creating many pushes that basically change the code a bit where there are potential bugs.

**Comment by marianheil** [comment]
I haven't used github actions before. Let me play around with them on my own mirror so you don't have to do anything for now. Whenever I have a setup that works well, I will come back.

For now we can just keep the current `flake8` setup and see how annoying it is.

**Comment by scarlehoff** [comment]
If you want I can give it a go, I've been moving things from travis to github workflow in the last few months.

**Comment by marianheil** [comment]
As you want, if you have time and feel like doing it, go ahead. As said its not a must have, just a neat little side project.

**Comment by scarlehoff** [comment]
>  just a neat little side project.
I agree, I like it more from the point of view of fiddling with workflows than the actual feature :__ I'll reopen then.

**Comment by scarlehoff** [comment]
Ok, no, I just changed opinion. Having an autolinter going through all the code everytime will potentially create many "fake changes" which makes reviewing PRs much more difficult, which in turns will make reviews worse.

**Pull request closed without merging**
