### PR TITLE
added setup.py for installation of pyhepgrid

### PR DESCRIPTION
**Pull request by scarlehoff**
This makes pyHepGrid looks nicer, the idea is that you do

    python setup.py install

or

    python setup.py develop

if you are planning to work on the code.

The "develop" installation basically installs the code as a symbolic link to the repository so that changes in the code are propagated to the installed version.

I've tested that nothing was _obviously_ broken but I cannot test whether this is actually true. Nothing has changed so if anything is broken is a missing "import pyHepGrid.src" instead of "import src".

### TODO:
- Generate a header for the user installing the code automatically, something along the line of:

      Your new header has been generated at $HOME/.pyHepGrid/$USER.py
      please change it as necessary.

### CODE REVIEW

**Comment by DWalker487** [comment]
I'm having some problems with this on the gridui. I ran 
`python3 setup.py install`
 which works ok, but I get for develop mode:
```
~/pyHepGrid$ python3 setup.py develop
running develop
error: ("Can't get a consistent path to setup script from installation directory", '/mt/home/dwalker', '/mt/home/dwalker/pyHepGrid')
```
which I don't understand (and there's no more debug output I can find). We also have an issue whereby the directory structure follows `pyHepGrid/src/pyHepGrid/src/<python source>` if one installs directly from github, which I don't think is particularly elegant? Let me know what you think.

**Comment by scarlehoff** [comment]
Strange, I can install it ok in the gridui (never seen that error). Maybe it is because the default python is python 2? I tried installing it but using a virtual environment with python3 as the default.

Yeah, the final src I agree it is a bit ugly, the better option is to break it into "backends" "utilities" and something like that. If the setup.py works I can do that reorganization easily.
The `pyhepgrid/src/pyhepgrid` part though I'd say it is ok. The module name is pyhepgrid after all.

**Comment by DWalker487** [comment]
Fixed it. it was an old version of setuptools on my personal installation of python3.6 In that case, go ahead and merge in. I'm currently working on a mode selection to disentangle Backend.py into program specific elements (NNLOJET/HEJ) by conditionally inheriting based on a header flag. I think that may be the most generic way of doing things, whilst still retaining examples for people to work with.

**Comment by scarlehoff** [comment]
Ok perfect. 
The merge is not going to be seamless because there seem to be a few conflicts so I'll commit the merge tomorrow (I'll merge master into this) before merging it into master.

**Comment by DWalker487** [comment]
Sounds good to me. On a side note, could we give marian r/w access to master? I think it would be useful to allow him to update things as he finds them, particularly w.r.t widening use etc.

**Comment by scarlehoff** [comment]
My personal opinion is that none of us should be committing directly to master but rather making PRs explaining the change (even if a typo) and merging.

But it might be me being too industrial.

**Comment by scarlehoff** [comment]
Ok, merging into master now.
I think I will try and take away w/r from master from everyone (without forcing) because thinking about it I like even more the idea that everything should go through PRs.
I don't know whether it is possible, but I'll try :_

**Comment by DWalker487** [comment]
Just had a thought - how will this work with our current header structure, which becomes installed as a package? As people frequently play around with the header, I guess everyone will have to install on develop mode as otherwise updates to it will not be reflected at runtime

**Comment by scarlehoff** [comment]
Yes, that is right. Actually I should open an issue about that.

**Pull request merged**
